target 'MusicalJournal' do
	# add the Firebase pod for Google Analytics
	pod 'Firebase'
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	# add pods for any other desired Firebase products
	# https://firebase.google.com/docs/ios/setup#available-"

	use_frameworks!
	pod 'NVActivityIndicatorView'
end
